openapi: 3.0.2
info:
  title: Yubisuma API
  description: |-
    <b>Yubisuma API仕様</b><br>
    Yubisumaに関するAPI
  version: 1.0.0
servers:
  - url: http://localhost:8080/
tags:
  - name: user
    description: ユーザ関連API
  - name: animals
    description: 動物関連API
  - name: action
    description: アクション関連API

paths:
  /animals:
    get:
      tags:
        - animals
      summary: 動物一覧取得
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  animals:
                    type: array
                    items:
                      $ref: "#/components/schemas/Animal"

  /animal:
    post:
      tags:
        - animals
      summary: 自分の動物選択
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AnimalPostRequest"
        required: true
      responses:
        200:
          description: Successfully selected the animal.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnimalPostResponse"

  /action:
    post:
      tags:
        - action
      summary: アクションの選択、表示
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Action"
        required: true
      responses:
        200:
          description: Successfully performed the action.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActionResponse"

components:
  schemas:
    Animal:
      type: object
      properties:
        id:
          type: string
          description: 動物のID
        name:
          type: string
          description: 動物名
        numFinger:
          type: integer
          description: 指の数
        skill:
          type: string
          description: スキル
        skillDesc:
          type: string
          description: スキルの説明文
        handUrl:
          type: string
          description: 手の画像URL
        upFingerUrl:
          type: string
          description: 上向きの指の画像URL
        downFingerUrl:
          type: string
          description: 下向きの指の画像URL

    AnimalPostRequest:
      type: object
      properties:
        id:
          type: string
          description: 動物のIDを選択

    AnimalPostResponse:
      type: object
      properties:
        isPlayer:
          type: boolean
          description: プレイヤーかどうか
        id:
          type: string
          description: 動物のID
        name:
          type: string
          description: 動物名
        numFinger:
          type: integer
          description: 指の数
        skill:
          type: string
          description: スキル
        skillDesc:
          type: string
          description: スキルの説明文
        handUrl:
          type: string
          description: 手の画像URL
        upFingerUrl:
          type: string
          description: 上向きの指の画像URL
        downFingerUrl:
          type: string
          description: 下向きの指の画像URL

    Action:
      type: object
      properties:
        isMyTurn:
          type: boolean
          description: 私のターンかどうか
        useSkill:
          type: boolean
          description: スキルを使用するかどうか
        numUpFinger:
          type: integer
          description: 上向きの指の数
        numClaimedFinger:
          type: integer
          description: 主張する指の数
          nullable: true

    ActionResponse:
      type: object
      properties:
        isFinished:
          type: boolean
          description: ゲームが終了したかどうか
        isMyTurn:
         
