version: '3'

services:
  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    command: tail -f /dev/null
  mysql:
    image: mysql/mysql-server:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "yubisuma_api"
    ports:
      - "3307:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: mysql
      PMA_USER: root
      PMA_PASSWORD: "password"
    ports:
      - "4000:80"
    links:
      - mysql
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    environment:
      SWAGGER_JSON: /api/api-document.yaml
    volumes:
      - ./api-document.yaml:/api/api-document.yaml:ro
    ports:
      - "127.0.0.1:8000:8080"

volumes:
  db-data:
    driver: local